import { useState } from "react";
import XLSX from "xlsx-js-style";
import api from "./api";

const normalize = (value) => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
const dateValue = (value) => { if (value instanceof Date) return `${String(value.getDate()).padStart(2, "0")}/${String(value.getMonth() + 1).padStart(2, "0")}/${value.getFullYear()}`; const text = String(value ?? "").trim(); if (/^\d{8}$/.test(text)) return `${text.slice(0, 2)}/${text.slice(2, 4)}/${text.slice(4)}`; if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return `${text.slice(8)}/${text.slice(5, 7)}/${text.slice(0, 4)}`; return text; };

export default function OfficeMeetingImportPage() {
  const [rows, setRows] = useState([]); const [fileName, setFileName] = useState(""); const [message, setMessage] = useState(null); const [saving, setSaving] = useState(false);
  const readFile = async (file) => { if (!file) return; try { const book = XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }); const sheet = book.Sheets[book.SheetNames.find((name) => normalize(name) !== "chu thich") || book.SheetNames[0]]; const data = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "" }); const headerIndex = data.findIndex((row) => row.some((cell) => ["so", "ngay hop", "noi dung"].includes(normalize(cell)))); if (headerIndex < 0) throw new Error("Không tìm thấy dòng tiêu đề Số/Ngày họp/Nội dung."); const headers = data[headerIndex].map(normalize); const parsed = data.slice(headerIndex + 1).map((row) => { const get = (...names) => { const index = names.map(normalize).map((n) => headers.indexOf(n)).find((i) => i >= 0); return index >= 0 ? row[index] : ""; }; return { number: String(get("Số")), meetingDate: dateValue(get("Ngày họp")), content: String(get("Nội dung")), attendeeCount: String(get("Số người họp") || 1), meetingType: String(get("Cuộc Họp") || "Họp Trực Tuyến") }; }).filter((row) => row.number || row.content); setRows(parsed); setFileName(file.name); setMessage({ type: "success", text: `Đã đọc ${parsed.length} dòng từ file.` }); } catch (error) { setRows([]); setMessage({ type: "danger", text: error.message || "Không thể đọc file Excel." }); } };
  const importRows = async () => { setSaving(true); let success = 0; try { for (const row of rows) { const form = new FormData(); Object.entries(row).forEach(([key, value]) => form.append(key === "meetingDate" ? "MeetingDate" : key === "meetingType" ? "MeetingType" : key === "attendeeCount" ? "AttendeeCount" : key[0].toUpperCase() + key.slice(1), value)); await api.post("/OfficeMeetings", form); success++; } setRows([]); setMessage({ type: "success", text: `Đã import thành công ${success} cuộc họp.` }); } catch (error) { setMessage({ type: "danger", text: error.response?.data?.message || `Đã import ${success}/${rows.length} dòng.` }); } finally { setSaving(false); } };
  return <section className="container-fluid py-2"><div className="card border-0 shadow-sm rounded-4 overflow-hidden"><div className="card-body p-4"><h2 className="h3 fw-bold mb-2">Import cuộc họp</h2><p className="text-muted">Chọn file Excel được xuất từ Danh sách họp. Hệ thống đọc các cột Số, Ngày họp, Nội dung, Số người họp và Cuộc Họp.</p>{message && <div className={`alert alert-${message.type}`}>{message.text}</div>}<input type="file" accept=".xlsx,.xls" className="form-control mb-3" onChange={(e) => readFile(e.target.files?.[0])} /><div className="small text-muted mb-3">{fileName || "Chưa chọn file"}</div>{rows.length > 0 && <><div className="table-responsive border rounded mb-3"><table className="table table-sm align-middle mb-0"><thead><tr><th>Số</th><th>Ngày họp</th><th>Nội dung</th><th>Số người họp</th><th>Cuộc Họp</th></tr></thead><tbody>{rows.slice(0, 20).map((row, index) => <tr key={index}><td>{row.number}</td><td>{row.meetingDate}</td><td>{row.content}</td><td>{row.attendeeCount}</td><td>{row.meetingType}</td></tr>)}</tbody></table></div><button className="btn btn-primary" onClick={importRows} disabled={saving}>{saving ? "Đang import..." : `Import ${rows.length} cuộc họp`}</button></>}</div></div></section>;
}
